- name: Install MySQL
  hosts: database
  become: yes
  tasks:
    - name: Install mysql-server package
      apt:
        name: mysql-server
        state: present
    - name: Restart MySQL service
      systemd:
        name: mysql
        state: restarted