- name : Mon Playbook !
  hosts: database
  become: true
  tasks:

    #like apt package manager
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install mysql Server
      apt:
        name:
          - mariadb-server
        state: latest

    - name: Install Git
      become: true
      apt:
        name: git
        state: present