- name : Mon Playbook !
  hosts: frontend
  become: true
  tasks:

    #like apt package manager
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install Node.js and NPM
      become: yes
      apt:
        name:
          - nodejs
          - npm

    - name: Install Angular CLI
      become: yes
      npm:
        name: '@angular/cli'
        global: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present
    

    